config/routes.rb
Rails.application.routes.draw do
  resources :collaborators#, only: [:create, :destroy]
  resources :wikis
  root 'welcome#index'
  get 'about' => 'welcome#about'
  devise_for :users
  resources :charges, only: [:new, :create]
  get 'downgrade' => 'charges#downgrade'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable

  validates :username, :presence => true, :uniqueness => {:case_sensitive => false}

  has_many :wikis
  has_many :collaborators
  has_many :wikis, through: :collaborators


  enum role: [:standard, :premium, :admin]
  after_initialize :set_default_role #after_initialize callback is triggered for each object that is found and instantiated by a finder, with after_initialize being triggered after new objects are instantiated as well.


  private

  def set_default_role
    self.role ||= :standard
  end


end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :collaborators
  has_many :users, through: :collaborators
  belongs_to :user

  scope :visible_to_login, -> (user) { user.admin? || user.premium? ? all : where(private: [false, nil])}
  scope :visible_to_all, -> {where(private: [false, nil])}
#  delegate :users, to: :collaborators


end

app/controllers/application_controller.rb
require 'will_paginate'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :configure_permitted_parameters, if: :devise_controller?
  #before_action :authenticate_user!

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end

    def user_not_authorized
      redirect_to(request.referrer || root_path)
      flash[:alert] = "You are not authorized to perform this action."

    end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  #stripe data on new page
  def new
    @amount = 500
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Wikey Cloney - #{current_user.username}",
      amount: @amount
    }
  end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
     @amount = 500

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: @amount,
      description: "Premium Blocipedia User - #{current_user.username}",
      currency: 'usd'
    )

    flash[:notice] = "Thanks for the subscription, #{current_user.username}! Hope you enjoy your premium account!"
    current_user.update_attribute(:role, 1)
    redirect_to wikis_path # or wherever

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end


    def downgrade
      current_user.update_attribute(:role, 0)
      current_user.wikis.update_all(:private => false)
      flash[:notice] = "We are sorry to downgrade you, #{current_user.username} - hope you enjoy being mediocre!"
      redirect_to wikis_path
    end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def index
  end
  def create
    @wiki = Wiki.find(params[:wiki_id])

    @user = User.where(email: params[:email]).take

    # is there a class method for this check?
    if @user == nil
      flash[:error] = "Collaborator could not be found."
      redirect_to edit_wiki_path(@wiki)
    elsif @wiki.collaborators.include?(@user)
      flash[:error] = "Collaborator already exists."
      redirect_to edit_wiki_path(@wiki)
    else
      collaborator = @wiki.collaborators.build(user_id: @user.id)

      if collaborator.save
        flash[:notice] = "Your collaborator has been added to the wiki."
        redirect_to edit_wiki_path(@wiki)
      else
        flash[:error] = "Collaborator could not be added. Check spelling!"
        redirect_to edit_wiki_path(@wiki)
      end
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    @wiki = @collaborator.wiki

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed from wiki."
      redirect_to @wiki
    else
      flash[:error] = "Collaborator could not be removed."
      redirect_to edit_wiki_path(@wiki)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
require 'will_paginate'

class WikisController < ApplicationController
  def index
    if current_user == nil
      @wikis = Wiki.visible_to_all
    else
      @wikis = policy_scope(Wiki)
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create

     @wiki = Wiki.new(wiki_params)
     @wiki.user = current_user
#     @wiki.title = params[:wiki][:title]
#     @wiki.body = params[:wiki][:body]

     if @wiki.save

       flash[:notice] = "Wiki was saved successfully."
       redirect_to @wiki
     else

       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :new
     end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]

    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated!"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end


  private
#expect these 4 attributes
   def wiki_params
     params.require(:wiki).permit(:title, :body, :private, :user)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(stuff)
   renderer = Redcarpet::Render::HTML.new
   extensions = {fenced_code_blocks: true, quote: true, autolink: true, underline: true}
   redcarpet = Redcarpet::Markdown.new(renderer, extensions= {})
   (redcarpet.render stuff).html_safe
 end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$$</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h3>Upgrade today for <strong>$<%=@stripe_btn_data[:amount]/100%></strong></h3>
  <div class= "stripe-card">
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
  </div>
<% end %>

app/views/collaborators/_collaborators.html.erb
  <%= form_tag collaborators_path, method: :post do %>
    <%= text_field_tag :email %>
    <%= hidden_field_tag :wiki_id, @wiki.id %>
    <%= submit_tag "Add Collaborator" %>
  <% end %>


</br>

<!-- displays list of collaborators -->
<div class="container">
  <div class="row">
    <h2>Collaborators:</h2>
    <% @wiki.collaborators.each do |collaborator| %>
      <p>
        <%= collaborator.user.email %>
        <!-- delete collaborator option only available to creator -->
        <% if @wiki.user == current_user %>
          <%= link_to "", [collaborator], method: :delete, class: 'glyphicon glyphicon-remove' %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/destroy.html.erb
<h1>Collaborators#destroy</h1>
<p>Find me in app/views/collaborators/destroy.html.erb</p>

app/views/layouts/_header.html.erb
<header>
  <div class= "clearfix">
    <div class = "row">
      <div class="col-lg-12">
        <nav>
          <% if user_signed_in? && current_user.standard?%>
              <ul class="nav nav-pills pull-left">
                <li role = "presentation"class="text-white"><%= link_to "Home", root_path, id: "logo", class: 'text-white' %></li>
                <li role = "presentation"class="text-white"><%= link_to "Wikis", wikis_path, id: "logo", class: 'text-white' %></li>
              </ul>
              <ul class="nav nav-pills pull-right">
                <li role = "presentation" class="text-white"><%= link_to "Try Premium!", new_charge_path, id: "logo", class: 'text-white' %></li>
                <li role = "presentation" class="text-white" ><%= link_to current_user.username, edit_user_registration_path, id: "logo", class: 'text-white' %>
                <li role = "presentation" class="text-white"><%= link_to "Logout", destroy_user_session_path, method: :delete, id: "logo", class: 'text-white' %></li>
                </li>
              </ul>

            <% elsif user_signed_in? && current_user.premium?%>
              <ul class="nav nav-pills pull-left">
                <li role = "presentation" class="text-white"><%= link_to "Home", root_path, id: "logo", class: 'text-white' %></li>
                <li role = "presentation" class="text-white"><%= link_to "Wikis", wikis_path, id: "logo", class: 'text-white' %></li>
              </ul>
              <ul class="nav nav-pills pull-right">
                <li role = "presentation" class="text-white"><%= link_to "Downgrade", downgrade_path, id: "logo", class: 'text-white'%></li>
                <li role = "presentation" class="text-white"><%= link_to current_user.username, edit_user_registration_path, id: "logo", class: 'text-white' %></li>
                <li role = "presentation" class="text-white"><%= link_to "Logout", destroy_user_session_path, method: :delete, id: "logo", class: 'text-white' %></li>
              </ul>

            <% elsif user_signed_in? && current_user.admin?%>
              <ul class="nav nav-pills pull-left">
                <li role = "presentation" class="text-white"><%= link_to "Home", root_path, id: "logo", class: 'text-white' %></li>
                <li role = "presentation" class="text-white"><%= link_to "Wikis", wikis_path, id: "logo", class: 'text-white' %></li>
              </ul>
              <ul class="nav nav-pills pull-right">
                <li role = "presentation" class="text-white"><%= link_to current_user.username, edit_user_registration_path, id: "logo", class: 'text-white' %></li>
                <li role = "presentation" class="text-white"><%= link_to "Logout", destroy_user_session_path, method: :delete, id: "logo", class: 'text-white' %></li>
              </ul>

            <% else %>
              <ul class="nav nav-pills pull-right">
                <li role = "presentation" class="text-white"><%= link_to "Sign up", new_user_registration_path, id: "logo", class: 'text-white' %></li>
                <li role = "presentation" class="text-white"><%= link_to "Login", new_user_session_path, id: "logo", class: 'text-white' %></li>
              </ul>
            <% end %>
          </nav>
        </div>
      </div>
    </div>
</header>

app/views/layouts/_header_wiki.html.erb
<header>
  <div class= "clearfix">
    <div class = "row">
      <div class="col-lg-12">
        <nav>
          <% if user_signed_in? && current_user.standard?%>
              <ul class="nav nav-pills pull-left">
                <li role = "presentation"class="text-white"><%= link_to "Home", root_path, id: "logo-wiki", class: 'text-white' %></li>
                <li role = "presentation"class="text-white"><%= link_to "Wikis", wikis_path, id: "logo-wiki", class: 'text-white' %></li>
              </ul>
              <ul class="nav nav-pills pull-right">
                <li role = "presentation" class="text-white"><%= link_to "Try Premium!", new_charge_path, id: "logo-wiki", class: 'text-white' %></li>
                <li role = "presentation" class="text-white" ><%= link_to current_user.username, edit_user_registration_path, id: "logo-wiki", class: 'text-white' %>
                <li role = "presentation" class="text-white"><%= link_to "Logout", destroy_user_session_path, method: :delete, id: "logo-wiki", class: 'text-white' %></li>
                </li>
              </ul>

            <% elsif user_signed_in? && current_user.premium?%>
              <ul class="nav nav-pills pull-left">
                <li role = "presentation" class="text-white"><%= link_to "Home", root_path, id: "logo-wiki", class: 'text-white' %></li>
                <li role = "presentation" class="text-white"><%= link_to "Wikis", wikis_path, id: "logo-wiki", class: 'text-white' %></li>
              </ul>
              <ul class="nav nav-pills pull-right">
                <li role = "presentation" class="text-white"><%= link_to "Downgrade", downgrade_path, id: "logo-wiki", class: 'text-white'%></li>
                <li role = "presentation" class="text-white"><%= link_to current_user.username, edit_user_registration_path, id: "logo-wiki", class: 'text-white' %></li>
                <li role = "presentation" class="text-white"><%= link_to "Logout", destroy_user_session_path, method: :delete, id: "logo-wiki", class: 'text-white' %></li>
              </ul>

            <% elsif user_signed_in? && current_user.admin?%>
              <ul class="nav nav-pills pull-left">
                <li role = "presentation" class="text-white"><%= link_to "Home", root_path, id: "logo-wiki", class: 'text-white' %></li>
                <li role = "presentation" class="text-white"><%= link_to "Wikis", wikis_path, id: "logo-wiki", class: 'text-white' %></li>
              </ul>
              <ul class="nav nav-pills pull-right">
                <li role = "presentation" class="text-white"><%= link_to current_user.username, edit_user_registration_path, id: "logo-wiki", class: 'text-white' %></li>
                <li role = "presentation" class="text-white"><%= link_to "Logout", destroy_user_session_path, method: :delete, id: "logo-wiki", class: 'text-white' %></li>
              </ul>

            <% else %>
              <ul class="nav nav-pills pull-right">
                <li role = "presentation" class="text-white"><%= link_to "Sign up", new_user_registration_path, id: "logo-wiki", class: 'text-white' %></li>
                <li role = "presentation" class="text-white"><%= link_to "Login", new_user_session_path, id: "logo-wiki", class: 'text-white' %></li>
              </ul>
            <% end %>
          </nav>
        </div>
      </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikey-Cloney</title>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Narrow Jumbotron Template for Bootstrap</title>
  <!-- Bootstrap core CSS -->
  <!--<link href="bootstrap/css/bootstrap.css" rel="stylesheet">-->
  <!-- Custom styles for this template -->
  <!--<link href="jumbotron-narrow.css" rel="stylesheet">-->
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash.now[:alert] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.now[:alert] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>



  <%= yield %>


    </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="col-md-12">
  <div class="jumbotron">
    <%= render 'layouts/header'%>
    <div class="container">

      <h1>Wikey-Cloney</h1>
      <p class="lead">Welcome to Wikey-Cloney, where we are posting and collaborating posts, everyday! </p>
      <p><%= link_to "Sign me up!", new_user_registration_path, class: "btn btn-lrg btn-primary"%></p>
    </div>
  </div>

  <div class="row marketing">
      <div class="col-lg-12">
        <h4>Feature1 (best feature)</h4>
        <p>Bacon ipsum dolor amet strip steak cow jowl hamburger t-bone tenderloin spare ribs jerky ribeye cupim shank andouille pig flank brisket. Ribeye pastrami rump filet mignon pancetta, jowl tri-tip shoulder bresaola venison cupim frankfurter swine ham. Swine meatball chuck pork strip steak flank pastrami. T-bone meatloaf ham turkey strip steak beef, chuck biltong tail andouille rump. Salami short loin bacon, sausage porchetta pork turkey venison pancetta. Landjaeger andouille t-bone pork turducken pork belly.</p>
        <h4>Feature2</h4>
        <p>Boudin meatloaf shank pastrami pancetta sirloin bresaola jerky. Turducken t-bone jerky pork loin ball tip ham pig beef tri-tip, bresaola meatloaf. Alcatra salami sausage biltong, brisket pork loin filet mignon chicken rump flank beef ribs. Beef ribs brisket picanha tongue turkey porchetta sirloin meatball swine. Pastrami turducken tri-tip, chuck ball tip sausage spare ribs porchetta filet mignon rump frankfurter. Ball tip brisket short loin frankfurter, turducken drumstick pork chop pork belly rump.</p>
        <h4>Feature3 (2nd best feature)</h4>
        <p>Ground round hamburger ball tip boudin turducken kielbasa tenderloin. Kielbasa short loin turkey pork hamburger. Tri-tip leberkas turducken, strip steak turkey boudin ribeye pork pastrami pork belly pancetta jowl chuck. Cupim picanha pork chop pork belly boudin ham hock, spare ribs ham swine chicken bacon landjaeger doner. Jowl hamburger short ribs pork belly, pork chop venison ground round tri-tip. Boudin meatloaf porchetta jowl flank strip steak leberkas. Andouille biltong short loin bacon chuck.</p>
      </div>
  </div>

  <footer class="footer pull-right">
      <p>&copy; <a href="mailto:letsmailiggy@gmail.com?Subject=You%20are%20awesome!" target="_top">Igor Irianto</a>, 2016</p>
  </footer>

</div>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/create.html.erb
<h1>Wikis#create</h1>
<p>Find me in app/views/wikis/create.html.erb</p>

app/views/wikis/delete.html.erb
<h1>Wikis#delete</h1>
<p>Find me in app/views/wikis/delete.html.erb</p>

app/views/wikis/destroy.html.erb
<h1>Wikis#delete</h1>
<p>Find me in app/views/wikis/delete.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Wikis</h1>
  <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>

      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
  <% end %>

  <div class="form-group">
    <%= render partial: 'collaborators/collaborators', locals: { wiki: @wiki, user: current_user } %>
  </div>

app/views/wikis/index.html.erb
<%= render 'layouts/header_wiki'%>
<h3>Wikis</h3>
<div class="row">
  <div class = "text-center main-text">
    <%= link_to "New", new_wiki_path, class: "btn btn-primary"%>
  </div>
</div>

<div class = "row">
  <div class = "col-lg-12">
    <% @wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to wiki.title, wiki %> <small><em>- by <%= wiki.user_id %></em></small>
        </h4>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
<h3>New Wiki</h3>

<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>

      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private, id: "private-check" %> Private?
          <% end %>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>

    <div class="form-group">
      <%= render partial: 'collaborators/collaborators', locals: { wiki: @wiki, user: current_user } %>
    </div>

  </div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %> <small> by <%= @wiki.user.username %></small></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>


<div class="container">
  <div class="row">
    <h4>List of Wiki Collaborators:</h4>
    <% @wiki.collaborators.each do |collaborator| %>
      <p>
        <%= collaborator.user.email %> <small><em> - user ID: <%= collaborator.user.id%></em></small>
        <!-- delete collaborator option only available to creator -->
        <% if @wiki.user.premium? || @wiki.user.admin? %>
          <%= link_to "Remove", @collaborator, method: :delete, class: 'glyphicon glyphicon-ok' %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>